import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Index from './LandingPage.js'

export default function Home() {
  return (
    <div>
      <Head>
        <title>SmartPharma</title>
        <link
          href="https://api.mapbox.com/mapbox-gl-js/v1.10.1/mapbox-gl.css"
          rel="stylesheet"
        />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Index/>
    </div>
  )
}
